name: generate-week-issue

on:
  # schedule:
  # - cron: "30 15 * * 6"
  # UTC SAT 15:30 = KST SUN 00:30
  # workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Setting
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install PyGitHub
      run: |
        python -m pip install --upgrade pip
        pip install 'PyGithub==1.55'
        pip install pytz
    - name: Generate Issue
      run: |
        python issue.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
